"""Emergency Handler node — handles life-threatening situations. ZERO LLM involvement."""

from __future__ import annotations

import logging

from synapse.state import SessionState

logger = logging.getLogger(__name__)

EMERGENCY_MESSAGES = {
    "en": {
        "cardiac": "This sounds like it could be serious. Please go to the Emergency Department immediately. Staff have been notified.",
        "neurological": "This requires immediate attention. Please proceed to the Emergency Department right away.",
        "trauma": "Please go directly to the Emergency Department. Do not wait. Medical staff are expecting you.",
        "psychiatric": "Your safety is our priority. Please proceed to the Emergency Department. Staff are ready to help you.",
        "obstetric": "This requires immediate medical attention. Please go to the Emergency Department now.",
        "respiratory": "This is a medical emergency. Please go to the Emergency Department immediately.",
        "default": "Please proceed to the Emergency Department immediately for urgent evaluation.",
    },
}


def emergency_handler(state: SessionState) -> dict:
    """Handle emergency: alert ED, log incident, display static message.

    This node is fully deterministic. No LLM calls.
    """
    emergency_type = state.get("emergency_type", "default")
    language = state.get("language", "en")
    session_id = state.get("session_id", "unknown")

    # Log the emergency
    logger.critical(
        "EMERGENCY DETECTED [%s] session=%s type=%s",
        session_id, session_id, emergency_type,
    )

    # Get pre-written emergency message (NOT generated by LLM)
    lang_messages = EMERGENCY_MESSAGES.get(language, EMERGENCY_MESSAGES["en"])
    patient_message = lang_messages.get(emergency_type, lang_messages["default"])

    return {
        "patient_facing_message": patient_message,
        "last_checkpoint_node": "emergency_handler",
    }
